### ISSUE TITLE
Sample .ipa file getting crashed in AWS Device farm

### ISSUE THREAD

**Issue by nitish-Datman** [King-of-Spades/AppCenter-Samples#60]
H,

i tried to build a CI pipeline thru AWS Device farm.. but not able to do with the same, as the ipa file(debug mode) is getting crashed everytime.. so i got a sample .ipa file from this repo.. but this too is getting crashed in AWS Device farm.

Is there any issue with building the .ipa file ??
 can you please help me with the same.??

Thanks,
Nitish

**Comment by King-of-Spades** [comment]
These samples aren't QA'd or designed with AWS device farm in mind. It's possible the bug is a valid issue, but we'd only generally be able to take a look at App Center specific issues. 

I've also migrated the most used (Xamarin.UITest) samples to official Microsoft repositories, where they're being more actively maintained: https://github.com/microsoft/appcenter/tree/master/sample-apps
